### ISSUE TITLE
Is this the repo for vippet.netlify.app? Why not link to this repo from that site?

### ISSUE THREAD

**Issue by JobLeonard** [mattorchard/vippet#1]
Hi, I came here through [a HN discussion](https://news.ycombinator.com/item?id=25288711) and I'm just wondering: assuming that this *is* the repo behind https://vippet.netlify.app/, was not including a link to this repo a conscious choice?

(and if it is the source repo: nice work!)

**Comment by mattorchard** [comment]
Hey, that's correct I haven't linked anything together since this project was a super quick one-weekend project (and my first one with svelte).

Here's another project I've made that deals with media recording [All Cap Site](https://allcap.netlify.app/), [and it's repo](https://github.com/mattorchard/all-capture)

Both are quite buggy, and neither will properly export if the document is hidden during export (since the request animation frame loop isn't permitted to continue at 60fps). But they're kinda fun little demos.

**Comment by mattorchard** [comment]
Thanks so much for taking the time to open this, really brightened my day!
I've added a link to the source from the site and a link to the site from the repo.
