### ISSUE TITLE
Add option to export to GIF

### ISSUE THREAD

**Issue by Tirzono** [mattorchard/vippet#2]
First of all: compliments for this project, it works so nice and simple.

I read it's a weekend project, but I would like to throw in a feature request: being able to export the video as a GIF. Maybe you can make use of:

https://github.com/jnordberg/gif.js

If you don't feel like doing this then I might start learning Svelte to see if I can build it in for you, but this might take a while since I never worked with Svelte.

**Comment by mattorchard** [comment]
I had thought about adding in a gif export option myself, and even took a look at that library.
I will definitely give it a try! 

Also I can whole heartedly recommend the [Svelte Interactive Tutorial](https://svelte.dev/tutorial) for trying to pick up svelte.
It lays stuff out step by step, but if you already have experience with other UI frameworks it's also super easy to jump around between topics and find exactly what you need!

**Comment by mattorchard** [comment]
Just added output resizing, another framerate option, and GIF EXPORTING! 

![preview of the new export form](https://user-images.githubusercontent.com/23462213/101232737-7ebe1680-3681-11eb-8271-e76ce6e56dd1.gif)

Fair warning the GIF exporter is a bit slower since it has to render _after_ capturing all the frames.
But with the addition of [worker timers](https://www.npmjs.com/package/worker-timers), exports can now happen even while you tab away from Vippet.

**Comment by Tirzono** [comment]
It works amazing, thank you for this addition, it's all I need to do a screen capture of a web page. You should consider posting this on Hackernews, I think more people will like it.
